version: '3'
services:
  db:
    image: postgres:13
    ports:
      - '5432:5432'
    volumes:
      - ./scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      POSTGRES_PASSWORD: password
  gql:
    image: graphtastic
    depends_on:
      - db
    ports:
      - '5000:5000'
    command: ['--connection', 'postgresql://postgres:password@db:5432/postgres',
              '--schema', 'public',
              '--watch',
              '--enhance-graphiql',
              '--cors', 
              '--append-plugins', '@graphile-contrib/pg-simplify-inflector,postgraphile-plugin-connection-filter']
