version: '3'
services:
  db:
    image: postgres:13
    ports:
      - '5432:5432'
    volumes:
      - ./scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./pagila:/var/opt/pagila
    environment:
      - POSTGRES_PASSWORD

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  gql:
    depends_on:
      - db
    image: graphtastic
    ports:
      - '5000:5000'
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    command: ['--connection', 'postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/postgres',
              '--schema', 'pagila',
              '--watch',
              '--dynamic-json',
              '--enhance-graphiql',
              '--no-ignore-rbac',
              '--cors', 
              '--append-plugins', '@graphile-contrib/pg-simplify-inflector,postgraphile-plugin-connection-filter']
